import { StyleSheet } from 'react-native';
import {
  STAGE_BOTTOM,
  RAISED,
  LINE,
  CHALK,
  DIM,
  GOLD,
  SELECT_GREEN,
} from './theme';

// --- Styles ---------------------------------------------------------------------------------

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: STAGE_BOTTOM },
  safe: { flex: 1 },
  loading: {
    flex: 1,
    backgroundColor: STAGE_BOTTOM,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: { padding: 24, paddingBottom: 56, flexGrow: 1 },

  orb: {
    position: 'absolute',
    width: 340,
    height: 340,
    borderRadius: 170,
    opacity: 0.16,
  },
  orbTopRight: { top: -140, right: -120 },
  orbBottomLeft: { bottom: -160, left: -140 },
  orbCenterFaint: { top: '38%', left: '30%', opacity: 0.05 },

  muteChip: {
    position: 'absolute',
    bottom: 24,
    right: 20,
    padding: 10,
  },
  muteChipText: { fontSize: 18 },
  backChip: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    padding: 10,
  },
  backChipText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: DIM,
  },
  igChip: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    padding: 10,
  },
  igChipLabel: {
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: '#6a5f96',
    marginBottom: 5,
  },
  igChipButton: {
    alignSelf: 'flex-start',
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: RAISED,
  },
  igChipHandle: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: CHALK,
  },
  landingDate: {
    fontSize: 12,
    letterSpacing: 3,
    fontWeight: '800',
    color: GOLD,
    textAlign: 'center',
    marginBottom: 14,
  },
  statRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 28,
    flexWrap: 'wrap',
  },
  statPill: {
    borderWidth: 1.5,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: RAISED,
  },
  statPillText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
    color: CHALK,
  },
  lastWeekText: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 14,
    color: DIM,
    textAlign: 'center',
    marginTop: -14,
    marginBottom: 28,
  },

  noticeBanner: {
    borderWidth: 1.5,
    borderColor: GOLD,
    borderRadius: 14,
    backgroundColor: 'rgba(255,200,74,0.1)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 22,
  },
  noticeBannerText: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 14,
    color: GOLD,
    textAlign: 'center',
    lineHeight: 20,
  },
  noticeBannerDismiss: {
    fontSize: 10,
    color: DIM,
    textAlign: 'center',
    marginTop: 5,
    letterSpacing: 1,
  },

  flavorBadge: {
    alignSelf: 'center',
    borderWidth: 1.5,
    borderColor: GOLD,
    borderRadius: 999,
    backgroundColor: 'rgba(255,200,74,0.08)',
    paddingHorizontal: 14,
    paddingVertical: 7,
    marginBottom: 16,
  },
  flavorBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: GOLD,
  },

  partnerLockedHint: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 13,
    color: DIM,
    textAlign: 'center',
    marginTop: -12,
    marginBottom: 20,
  },

  skipQuestionCard: {
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 16,
    backgroundColor: RAISED,
    padding: 16,
    marginBottom: 26,
  },
  skipQuestionLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: DIM,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
  },
  skipQuestionText: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 16,
    color: CHALK,
    textAlign: 'center',
    lineHeight: 23,
  },
  declineButton: {
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 12,
    backgroundColor: RAISED,
  },
  declineButtonText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 2,
    color: CHALK,
  },

  dotsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 24,
    paddingBottom: 6,
    paddingTop: 10,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: LINE,
  },

  kicker: {
    fontSize: 12,
    letterSpacing: 3,
    fontWeight: '800',
    marginBottom: 12,
    textAlign: 'center',
    alignSelf: 'center',
  },
  question: {
    fontFamily: 'Fraunces_900Black',
    fontSize: 32,
    color: CHALK,
    lineHeight: 38,
    marginBottom: 24,
    textAlign: 'center',
  },
  questionItalic: { fontFamily: 'Fraunces_900Black_Italic' },
  answerPage: {
    flex: 1,
    justifyContent: 'center',
  },
  landing: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 40,
  },
  landingCenter: {
    flex: 1,
    justifyContent: 'center',
  },
  landingTitle: {
    fontFamily: 'Fraunces_900Black_Italic',
    fontSize: 76,
    color: CHALK,
    textAlign: 'center',
    marginBottom: 6,
  },
  landingTagline: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 17,
    color: DIM,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 36,
  },
  authInput: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 16,
    color: CHALK,
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 16,
    backgroundColor: RAISED,
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginBottom: 12,
  },
  authInfo: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 13,
    color: SELECT_GREEN,
    textAlign: 'center',
    marginBottom: 14,
  },
  codeInput: {
    textAlign: 'center',
    letterSpacing: 8,
    fontSize: 22,
  },
  inviteCodeBox: {
    borderWidth: 2,
    borderColor: GOLD,
    borderRadius: 20,
    backgroundColor: 'rgba(255,200,74,0.08)',
    paddingHorizontal: 30,
    paddingVertical: 20,
    marginBottom: 24,
  },
  inviteCodeText: {
    fontFamily: 'Fraunces_900Black',
    fontSize: 40,
    letterSpacing: 10,
    color: GOLD,
  },
  shareButton: {
    backgroundColor: GOLD,
    borderRadius: 16,
    paddingHorizontal: 28,
    paddingVertical: 15,
    marginTop: 26,
    marginBottom: 8,
  },
  shareButtonText: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 2,
    color: STAGE_BOTTOM,
  },
  authError: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 13,
    color: '#ff8fa0',
    textAlign: 'center',
    marginBottom: 14,
  },
  landingFooter: {
    fontSize: 12,
    color: '#6a5f96',
    textAlign: 'center',
    letterSpacing: 0.5,
  },

  optionGroup: { gap: 10, marginBottom: 28 },

  wagerBlock: { marginTop: -8, marginBottom: 28, alignItems: 'center' },
  wagerLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: DIM,
    fontWeight: '700',
    marginBottom: 10,
  },
  wagerRow: { flexDirection: 'row', gap: 10 },
  wagerChip: {
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 16,
    backgroundColor: RAISED,
    paddingHorizontal: 20,
    paddingVertical: 10,
    alignItems: 'center',
    minWidth: 86,
  },
  wagerChipValue: { fontFamily: 'Fraunces_900Black', fontSize: 20, color: CHALK },
  wagerChipCaption: { fontSize: 10, letterSpacing: 1, color: DIM, marginTop: 2 },
  wagerHint: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 13,
    color: DIM,
    marginTop: 12,
    textAlign: 'center',
  },
  option: {
    borderWidth: 1.5,
    borderColor: LINE,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    backgroundColor: RAISED,
    alignItems: 'center',
  },
  optionText: {
    fontFamily: 'Fraunces_600SemiBold',
    fontSize: 18,
    color: CHALK,
  },

  primaryButton: {
    backgroundColor: GOLD,
    borderRadius: 16,
    paddingVertical: 17,
    alignItems: 'center',
  },
  primaryButtonDisabled: {
    backgroundColor: RAISED,
    borderWidth: 1,
    borderColor: LINE,
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 2,
    color: STAGE_BOTTOM,
  },

  backLink: { alignItems: 'center', paddingVertical: 18 },
  backLinkText: { color: DIM, fontSize: 14 },

  centered: { alignItems: 'center', paddingTop: 64, paddingHorizontal: 12 },
  lockBadge: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
    backgroundColor: RAISED,
  },
  lockEmoji: { fontSize: 36 },
  waitingTitle: {
    fontFamily: 'Fraunces_900Black',
    fontSize: 30,
    color: CHALK,
    marginBottom: 12,
    textAlign: 'center',
  },
  waitingSub: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 17,
    color: DIM,
    textAlign: 'center',
    lineHeight: 26,
  },
  debugHint: { fontSize: 12, color: '#6a5f96', marginTop: 32, textAlign: 'center' },

  waitingChip: {
    alignSelf: 'center',
    borderWidth: 1.5,
    borderColor: GOLD,
    borderRadius: 999,
    backgroundColor: 'rgba(255,200,74,0.08)',
    paddingHorizontal: 16,
    paddingVertical: 9,
    marginBottom: 16,
  },
  waitingChipText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.5,
    color: GOLD,
  },
  codeCard: {
    borderWidth: 2,
    borderColor: GOLD,
    borderRadius: 20,
    backgroundColor: 'rgba(255,200,74,0.08)',
    paddingHorizontal: 28,
    paddingVertical: 16,
    marginBottom: 14,
    alignItems: 'center',
  },
  codeCardText: {
    fontFamily: 'Fraunces_900Black',
    fontSize: 34,
    letterSpacing: 8,
    color: GOLD,
  },
  codeCardHint: {
    fontSize: 10,
    letterSpacing: 1.5,
    color: DIM,
    marginTop: 6,
  },
  revealCard: {
    backgroundColor: 'rgba(20,12,44,0.82)',
    borderRadius: 20,
    borderWidth: 2,
    padding: 18,
    paddingTop: 24,
  },
  revealNameTag: {
    position: 'absolute',
    top: -13,
    left: 16,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  revealNameText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    color: STAGE_BOTTOM,
  },
  revealAnswerLabel: {
    fontSize: 10,
    letterSpacing: 2,
    color: DIM,
    fontWeight: '700',
    marginBottom: 4,
  },
  revealAnswer: {
    fontFamily: 'Fraunces_900Black',
    fontSize: 26,
    marginBottom: 12,
  },
  revealPrediction: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 14,
    color: DIM,
    marginBottom: 14,
    lineHeight: 21,
  },
  verdict: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  verdictText: { fontSize: 12, fontWeight: '900', letterSpacing: 1 },

  vsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 18,
  },
  vsLine: { flex: 1, height: 1, backgroundColor: LINE },
  vsText: {
    fontFamily: 'Fraunces_900Black_Italic',
    color: GOLD,
    fontSize: 18,
  },

  scoreHeadline: {
    fontFamily: 'Fraunces_900Black_Italic',
    fontSize: 22,
    color: GOLD,
    textAlign: 'center',
    marginTop: 26,
    marginBottom: 16,
  },
  scoreRow: { flexDirection: 'row', gap: 12, justifyContent: 'center' },
  scorePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: RAISED,
  },
  scorePillName: { fontSize: 14, fontWeight: '800' },
  scorePillPoints: { fontSize: 14, fontWeight: '900', color: CHALK },

  revealFooter: {
    fontFamily: 'Fraunces_400Regular',
    fontSize: 14,
    color: DIM,
    textAlign: 'center',
    paddingVertical: 22,
    marginTop: 8,
  },
});
